ezsystems/ezplatform-matrix-fieldtype

.prettierrc, src/bundle/DependencyInjection/EzPlatformMatrixFieldtypeExtension.php, src/bundle/Resources/config/kernel.yml, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/components.yml, src/bundle/Resources/config/services/fieldtype.yml, src/bundle/Resources/encore/ez.config.js, src/bundle/Resources/public/js/scripts/admin.contenttype.matrix.js, src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js, src/bundle/Resources/schema/legacy_matrix.xsd, src/bundle/Resources/translations/fieldtypes.en.xliff, src/bundle/Resources/translations/matrix_fieldtype.en.xliff, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/javascripts.component.html.twig, src/bundle/Resources/views/themes/standard/matrix_fieldtype/content_fields.html.twig, src/lib/FieldType/Converter/MatrixConverter.php, src/lib/FieldType/Mapper/MatrixFormMapper.php, src/lib/FieldType/Type.php, src/lib/FieldType/Value.php, src/lib/FieldType/Value/Row.php, src/lib/FieldType/Value/RowsCollection.php, src/lib/Form/Transformer/FieldTypeModelTransformer.php, src/lib/Form/Type/ColumnType.php, src/lib/Form/Type/FieldType/MatrixCollectionType.php, src/lib/Form/Type/FieldType/MatrixEntryType.php, src/lib/Form/Type/FieldType/MatrixFieldType.php
JIRA: https://jira.ez.no/browse/EZP-26686
=> EZP-26686: Add eZ Matrix Field Type to the Platform as a supported bundle

src/bundle/Resources/config/kernel.yml, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
=> Fixed "Cannot find 'ezmatrix_field' template block." exception

src/bundle/Resources/views/themes/standard/matrix_fieldtype/content_fields.html.twig
=> fix: Update ezmatrix_field frontend template after recent changes to model

src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js
JIRA: https://jira.ez.no/browse/EZP-30225
=> EZP-30225: Fix matrix row deletion by content publish/save

src/lib/FieldType/Converter/MatrixConverter.php, src/lib/FieldType/Type.php
JIRA: https://jira.ez.no/browse/EZP-30238
=> EZP-30238: Fix empty matrix values during edition of content

src/lib/FieldType/Converter/MatrixConverter.php, src/lib/FieldType/Type.php
JIRA: https://jira.ez.no/browse/EZP-30226
=> EZP-30226: Add field type config validation during Content Type create/edit

src/bundle/Resources/config/kernel.yml
JIRA: https://jira.ez.no/browse/EZP-29724
Remove quick-fix as it is no longer needed because of changes to Kernel and Standard Design:
- https://github.com/ezsystems/ezplatform-standard-design/pull/4
- https://github.com/ezsystems/ezpublish-kernel/pull/2554
=> EZP-29724: Remove obsolete config entry (follow up to Kernel ticket)

src/lib/FieldType/Type.php
JIRA: https://jira.ez.no/browse/EZP-30260
=> EZP-30260: Fixed error when publishing empty, non-required matrix

src/bundle/Resources/public/js/scripts/admin.contenttype.matrix.js, src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
JIRA: https://jira.ez.no/browse/EZP-30301
=> EZP-30301: Fixed Matrix field type incorrect index

src/bundle/Command/MigrateLegacyMatrixCommand.php
JIRA: https://jira.ez.no/browse/EZP-30875
=> EZP-30875: Allow to run migrate command in --no-interaction mode

composer.json, src/lib/FieldType/Mapper/MatrixFormMapper.php
> JIRA: https://jira.ez.no/browse/EZP-31009
This PR adds dependency to `ezplatform-content-forms` instead of `repository-forms`.
=> EZP-31009: Updated namespaces in ezplatform-matrix-fieldtype

.php_cs, .travis.yml, composer.json, src/lib/GraphQL/FieldValueResolver.php, src/lib/GraphQL/InputHandler.php, src/lib/GraphQL/Schema/MatrixFieldDefinitionInputSchemaWorker.php, src/lib/GraphQL/SilentRow.php
This PR:
1) Adds a CS job to this repository (together with notifications)
2) Adds our internal CS config
3) Fixes CS according to it
=> Add basic Travis setup

.gitignore, .php_cs, .travis.yml, composer.json, phpunit-integration-legacy.xml, src/bundle/Resources/config/services/fieldtype.yml, src/lib/FieldType/Indexable.php, src/lib/FieldType/Type.php, tests/integration/API/Repository/SearchServiceTest.php, tests/integration/CoreSetupFactoryTrait.php, tests/integration/LegacySetupFactory.php
> JIRA: https://jira.ez.no/browse/EZP-31264
Basic impl. `eZ\Publish\SPI\FieldType\Indexable` for the `ezmatrix` field type.
=> EZP-31264: Implemented Indexable for ezmatrix FT

src/bundle/Resources/views/themes/standard/matrix_fieldtype/content_fields.html.twig
**JIRA**: https://jira.ez.no/browse/EZP-31265
Updated field template to render attr.class if passed.
=> EZP-31265 - Add support for attr.class

src/bundle/Resources/config/services/migration.yml
Question      | Answer
| ------------- | ---
| Tickets       | [EZP-31342](https://jira.ez.no/browse/EZP-31342)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
=> EZP-31342: Added argument to service, to use valid database connection

.travis.yml, .travis/prepare_ezplatform.sh, composer.json
Done as part of: https://jira.ez.no/browse/EZP-31311
Running fieldtypes tests when a PR for this repository is created
Merging upstream:
=> [Travis] Added job with browser fieldtypes tests

src/bundle/Command/MigrateLegacyMatrixCommand.php
Please check https://jira.ez.no/browse/EZP-31522 for details.
=> EZP-31522: Exist status code added

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
jira ref: https://jira.ez.no/browse/EZP-31774
=> EZP-31774: Update content content create

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
**Jira ticket:** https://jira.ez.no/browse/EZP-31721
=> EZP-31721: New UI

src/lib/FieldType/Converter/MatrixConverter.php
Jira ticket: https://jira.ez.no/browse/EZP-31829
=> EZP-31829: Added condition for dataText in toFieldValue to prevented decoding dataText as null

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
JIRA ref: https://jira.ez.no/browse/EZP-31941
=> EZP-31941: A row in the tables under Admin panel should have a gray background on hover over (Same as rest of the application)

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig
JIRA ref: https://jira.ez.no/browse/EZP-32024
=> EZP-32024: Icon inside row tables should be grey

src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
jira ref: https://jira.ez.no/browse/EZP-32048
=> EZP-32048: Content Type - buttons in ezmatrix are not styled properly

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
JIRA ref: https://jira.ez.no/browse/EZP-32078
=> EZP-32078: Update icon path

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
jira ref: https://issues.ibexa.co/browse/EZP-32212
Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1662
=> Moved tables to div with class ez-scrollable-table-wrapper

src/bundle/Resources/public/js/scripts/admin.contenttype.matrix.js, src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
Main PR: ezsystems/ezplatform-admin-ui#1755
=> IBX-268: Redesign buttons for 4.0

src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig
JIRA ref: https://issues.ibexa.co/browse/IBX-615
https://github.com/ezsystems/date-based-publisher/pull/227
https://github.com/ezsystems/ezcommerce-admin-ui/pull/92
https://github.com/ezsystems/ezcommerce-shop/pull/323
https://github.com/ezsystems/ezplatform-admin-ui/pull/1793
https://github.com/ezsystems/ezplatform-calendar/pull/76
https://github.com/ezsystems/ezplatform-form-builder/pull/286
https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/55
https://github.com/ezsystems/ezplatform-page-builder/pull/777
https://github.com/ezsystems/ezplatform-page-fieldtype/pull/189
https://github.com/ezsystems/ezplatform-personalization/pull/212
https://github.com/ezsystems/ezplatform-segmentation/pull/30
https://github.com/ezsystems/ezplatform-site-factory/pull/126
=> IBX-615: As an Editor, I want to see redesigned checkbox and radio buttons in all states

src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-612
=> IBX-612: As an Editor, I want to see redesigned input field in all states (with labels)

src/bundle/Resources/public/js/scripts/admin.contenttype.matrix.js, src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig, src/bundle/Resources/views/themes/admin/matrix_fieldtype/field_types.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-492
=> IBX-492: As an Editor, I want to see redesigned tables

src/bundle/Resources/encore/ez.config.manager.js, src/bundle/Resources/public/js/scripts/fieldType/ezmatrix.js, src/bundle/Resources/public/scss/fieldType/_ezmatrix.scss, src/bundle/Resources/public/scss/matrix.scss, src/bundle/Resources/translations/matrix_fieldtype.en.xliff, src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_edit_form_fields.html.twig
https://issues.ibexa.co/browse/IBX-636
=> IBX-636: Redesigned ezmatrix
